name: translation_app
version: 0.1.7+2014
resolution: workspace

publish_to: 'none'

environment:
  sdk: "^3.10.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.5
  share_plus: ^12.0.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  receive_sharing_intent: ^1.8.1
  
  # Internal packages
  translation_core:
    path: ../packages/translation_core
  file_handler:
    path: ../packages/file_handler
  history:
    path: ../packages/history
  markdown_renderer:
    path: ../packages/markdown_renderer
  flutter_overlay_window: ^0.5.0
  flutter_markdown_plus: ^1.0.7
  markdown: ^7.3.1
  url_launcher: ^6.2.5
  http: ^1.2.0
  dio: ^5.4.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/articles/
