name: markdown_renderer
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.10.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0